// <auto-generated />
using System;
using Eventos.Infraestructura.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eventos.Infraestructura.Migrations
{
 [DbContext(typeof(EventsDbContext))]
 [Migration("20251110135350_InitialCreate")]
 partial class InitialCreate : Migration
 {
 /// <inheritdoc />
 protected override void BuildTargetModel(ModelBuilder modelBuilder)
 {
#pragma warning disable612,618
 modelBuilder
 .HasAnnotation("ProductVersion", "8.0.0")
 .HasAnnotation("Relational:MaxIdentifierLength",63);

 NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

 modelBuilder.Entity("Eventos.Dominio.Entidades.Asistente", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<string>("Correo")
 .IsRequired()
 .HasMaxLength(300)
 .HasColumnType("character varying(300)");

 b.Property<Guid>("EventoId")
 .HasColumnType("uuid");

 b.Property<DateTime>("RegistradoEn")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("UsuarioId")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b.Property<string>("NombreUsuario")
 .IsRequired()
 .HasMaxLength(200)
 .HasColumnType("character varying(200)");

 b.HasKey("Id");

 b.HasIndex("EventoId", "UsuarioId")
 .IsUnique();

 b.ToTable("Attendees");
 });

 modelBuilder.Entity("Eventos.Dominio.Entidades.Evento", b =>
 {
 b.Property<Guid>("Id")
 .ValueGeneratedOnAdd()
 .HasColumnType("uuid");

 b.Property<DateTime>("CreatedAt")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("Descripcion")
 .IsRequired()
 .HasMaxLength(2000)
 .HasColumnType("character varying(2000)");

 b.Property<DateTime>("FechaFin")
 .HasColumnType("timestamp with time zone");

 b.Property<int>("MaximoAsistentes")
 .HasColumnType("integer");

 b.Property<string>("OrganizadorId")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b.Property<DateTime>("FechaInicio")
 .HasColumnType("timestamp with time zone");

 b.Property<string>("Estado")
 .IsRequired()
 .HasColumnType("text");

 b.Property<string>("Titulo")
 .IsRequired()
 .HasMaxLength(200)
 .HasColumnType("character varying(200)");

 b.Property<DateTime?>("UpdatedAt")
 .HasColumnType("timestamp with time zone");

 b.HasKey("Id");

 b.HasIndex("OrganizadorId");

 b.HasIndex("FechaInicio");

 b.HasIndex("Estado");

 b.ToTable("Events");
 });

 modelBuilder.Entity("Eventos.Dominio.Entidades.Asistente", b =>
 {
 b.HasOne("Eventos.Dominio.Entidades.Evento", null)
 .WithMany("Asistentes")
 .HasForeignKey("EventoId")
 .OnDelete(DeleteBehavior.Cascade)
 .IsRequired();
 });

 modelBuilder.Entity("Eventos.Dominio.Entidades.Evento", b =>
 {
 b.OwnsOne("Eventos.Dominio.ObjetosDeValor.Ubicacion", "Ubicacion", b1 =>
 {
 b1.Property<Guid>("EventId")
 .HasColumnType("uuid");

 b1.Property<string>("Direccion")
 .IsRequired()
 .HasMaxLength(300)
 .HasColumnType("character varying(300)");

 b1.Property<string>("Ciudad")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b1.Property<string>("Pais")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b1.Property<string>("CodigoPostal")
 .IsRequired()
 .HasMaxLength(20)
 .HasColumnType("character varying(20)");

 b1.Property<string>("Region")
 .IsRequired()
 .HasMaxLength(100)
 .HasColumnType("character varying(100)");

 b1.Property<string>("NombreLugar")
 .IsRequired()
 .HasMaxLength(200)
 .HasColumnType("character varying(200)");

 b1.HasKey("EventId");

 b1.ToTable("Events");

 b1.WithOwner()
 .HasForeignKey("EventId");
 });

 b.Navigation("Ubicacion")
 .IsRequired();
 });

 modelBuilder.Entity("Eventos.Dominio.Entidades.Evento", b =>
 {
 b.Navigation("Asistentes");
 });
#pragma warning restore612,618
 }
 }
}
